#!/usr/bin/env python3
"""Generates src/jni_slots.inc: names + logging stubs for all 233 JNIEnv slots."""
import os

names = ["reserved0", "reserved1", "reserved2", "reserved3", "GetVersion", "DefineClass", "FindClass",
         "FromReflectedMethod", "FromReflectedField", "ToReflectedMethod", "GetSuperclass", "IsAssignableFrom",
         "ToReflectedField", "Throw", "ThrowNew", "ExceptionOccurred", "ExceptionDescribe", "ExceptionClear",
         "FatalError", "PushLocalFrame", "PopLocalFrame", "NewGlobalRef", "DeleteGlobalRef", "DeleteLocalRef",
         "IsSameObject", "NewLocalRef", "EnsureLocalCapacity", "AllocObject", "NewObject", "NewObjectV", "NewObjectA",
         "GetObjectClass", "IsInstanceOf", "GetMethodID"]
types = ["Object", "Boolean", "Byte", "Char", "Short", "Int", "Long", "Float", "Double", "Void"]
for t in types:
    names += [f"Call{t}Method", f"Call{t}MethodV", f"Call{t}MethodA"]
for t in types:
    names += [f"CallNonvirtual{t}Method", f"CallNonvirtual{t}MethodV", f"CallNonvirtual{t}MethodA"]
names += ["GetFieldID"]
ft = types[:-1]
names += [f"Get{t}Field" for t in ft]
names += [f"Set{t}Field" for t in ft]
names += ["GetStaticMethodID"]
for t in types:
    names += [f"CallStatic{t}Method", f"CallStatic{t}MethodV", f"CallStatic{t}MethodA"]
names += ["GetStaticFieldID"]
names += [f"GetStatic{t}Field" for t in ft]
names += [f"SetStatic{t}Field" for t in ft]
names += ["NewString", "GetStringLength", "GetStringChars", "ReleaseStringChars", "NewStringUTF",
          "GetStringUTFLength", "GetStringUTFChars", "ReleaseStringUTFChars", "GetArrayLength", "NewObjectArray",
          "GetObjectArrayElement", "SetObjectArrayElement"]
pt = types[1:-1]
names += [f"New{t}Array" for t in pt]
names += [f"Get{t}ArrayElements" for t in pt]
names += [f"Release{t}ArrayElements" for t in pt]
names += [f"Get{t}ArrayRegion" for t in pt]
names += [f"Set{t}ArrayRegion" for t in pt]
names += ["RegisterNatives", "UnregisterNatives", "MonitorEnter", "MonitorExit", "GetJavaVM", "GetStringRegion",
          "GetStringUTFRegion", "GetPrimitiveArrayCritical", "ReleasePrimitiveArrayCritical", "GetStringCritical",
          "ReleaseStringCritical", "NewWeakGlobalRef", "DeleteWeakGlobalRef", "ExceptionCheck",
          "NewDirectByteBuffer", "GetDirectBufferAddress", "GetDirectBufferCapacity", "GetObjectRefType"]
assert len(names) == 233, len(names)

out = ["/* GENERATED by tools/gen_jni_slots.py - do not edit */",
       "#define JNI_SLOTS 233",
       "static const char *const jni_slot_names[JNI_SLOTS] = {"]
out += [f'    "{n}",' for n in names]
out += ["};", ""]
for i in range(233):
    out.append(f"static intptr_t ju_{i}(void) {{ jni_unimpl({i}); return 0; }}")
out += ["", "static void *jni_table[JNI_SLOTS] = {"]
out += [f"    (void *)ju_{i}," for i in range(233)]
out += ["};", "", "enum {"]
out += [f"    JNI_{n.upper() if False else n} = {i}," for i, n in enumerate(names)]
out += ["};", ""]
dst = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "src", "jni_slots.inc")
os.makedirs(os.path.dirname(dst), exist_ok=True)
open(dst, "w").write("\n".join(out))
print("wrote", os.path.normpath(dst), len(names), "slots")
